/**
 * Server entry point
 */
import { networkInterfaces } from 'node:os'
import { buildApp, type AppOptions } from './app.ts'
import { initDatabase } from './db/index.ts'
import type { ServerConfig } from './config.ts'

export interface StartServerOptions extends Omit<AppOptions, 'db'> {
  tokenAutoGenerated?: boolean;
  certificatePath?: string; // Path to certificate file for logging
}

/**
 * Get all IPv4 addresses to display when server binds to 0.0.0.0
 */
function getNetworkAddresses (): string[] {
  const addresses: string[] = ['127.0.0.1']
  const interfaces = networkInterfaces()

  for (const nets of Object.values(interfaces)) {
    if (!nets) continue
    for (const net of nets) {
      // Include non-internal IPv4 addresses
      if (!net.internal && net.family === 'IPv4') {
        addresses.push(net.address)
      }
    }
  }

  return addresses
}

export async function startServer (config: ServerConfig, options: StartServerOptions = {}): Promise<void> {
  // Initialize database and pass to app via options
  const db = initDatabase(config.dbPath)

  // Build and start the app
  const app = await buildApp(config, { ...options, db })

  // Log if token was auto-generated
  if (options.tokenAutoGenerated) {
    app.log.info('Auth token auto-generated')
  }

  // Log certificate path if using HTTPS
  if (config.https && options.certificatePath) {
    app.log.info(`Using certificate from ${options.certificatePath}`)
  }

  // Graceful shutdown with timeout
  const shutdown = async () => {
    app.log.info('Shutting down...')
    const timer = setTimeout(() => process.exit(1), 5000)
    try {
      await app.close()
      db.close()
    } finally {
      clearTimeout(timer)
    }
  }
  process.on('SIGTERM', shutdown)
  process.on('SIGINT', shutdown)

  try {
    await app.listen({ port: config.port, host: config.host })

    // Log URLs with token for easy access (double-clickable in terminals)
    const serverAddr = app.addresses().find(a => a.family === 'IPv4')
    if (serverAddr) {
      // If bound to 0.0.0.0, show all network addresses
      const addresses = serverAddr.address === '0.0.0.0'
        ? getNetworkAddresses()
        : [serverAddr.address]

      const protocol = config.https ? 'https' : 'http'
      for (const addr of addresses) {
        const url = config.authToken
          ? `${protocol}://${addr}:${serverAddr.port}?token=${encodeURIComponent(config.authToken)}`
          : `${protocol}://${addr}:${serverAddr.port}`
        app.log.info(`GitHuman running at: ${url}`)
      }
    }
  } catch (err) {
    app.log.error(err)
    db.close()
    throw err
  }
}

export { buildApp } from './app.ts'
export { createConfig, generateToken } from './config.ts'
export type { ServerConfig } from './config.ts'
